name: Run test cases

on:
  pull_request:
  push:
    branches:
      - 'master'

jobs:
  run_test_cases:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        builder:
          - "1.15.7-26.2.5.2-3-ubuntu22.04"
          - "1.17.3-27.2-2-ubuntu22.04"

    container:
      image: "ghcr.io/emqx/emqx-builder/5.5-0:${{ matrix.builder }}"

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: check formatting
        run: make fmt-check
      - name: run xref checks
        run: make xref
      - name: run test cases
        run: |
          make eunit  
          make ct
          make cover
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        if: always()
        with:
          name: "logs-${{ matrix.builder }}"
          path: _build/test/logs
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: "cover-${{ matrix.builder }}"
          path: _build/test/cover
