name: Run test cases

on: [push, pull_request]

jobs:    
    run_test_cases:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                otp: [22.1, 23.3, 24.0.2]

        container:
            image: erlang:${{ matrix.otp }}

        steps:
            - uses: actions/checkout@v1
            - name: run test cases
              run: |
                make xref
                make eunit  
                make ct
                make cover
            - uses: actions/upload-artifact@v1
              if: always()
              with:
                name: logs
                path: _build/test/logs
            - uses: actions/upload-artifact@v1
              with:
                name: cover
                path: _build/test/cover

