name: Run test cases

on: [push, pull_request]

jobs:
    run_test_cases:
        runs-on: ubuntu-latest

        container:
            image: ghcr.io/emqx/emqx-builder/5.3-13:1.15.7-26.2.5.2-1-ubuntu22.04

        steps:
            - uses: actions/checkout@v4
            - name: check formatting
              run: make fmt-check
            - name: run xref checks
              run: make xref
            - name: run test cases
              run: |
                make eunit  
                make ct
                make cover
            - uses: actions/upload-artifact@v4
              if: always()
              with:
                name: logs
                path: _build/test/logs
            - uses: actions/upload-artifact@v4
              with:
                name: cover
                path: _build/test/cover

